name: CI/CD Pipeline for Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK for building the Spring Boot application
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Or adopt, zulu, etc.
          java-version: '22'

      # Step 3: Build the Spring Boot application using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app .

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app
